version: '3.8'

services:
  soundcloud-bot:
    build: .
    container_name: soundcloud-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./temp:/app/temp
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
